---
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: pdflatex
    template: syllabus-template.tex #From http://svmiller.com/blog/2016/07/r-markdown-syllabus/
  html_document:
    df_print: paged
geometry: margin=1in

title: "Econ 235: Introduction to Agricultural Markets"
subtitle: "Iowa State University"
author: Sébastien Pouliot
date: "Fall 2018"

email: "pouliot@iastate.edu"
officehours: "W 10:00-11:00 am or by appointment"
office: "468-G Heady Hall"
classroom: "NSRIC 1131"
classhours: "TR 9:30-10:50am"
assistant: 

font-family: Calibri
fontsize: 11pt
header-includes:
   - \linespread{1.05}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course Description
Econ 235 introduces you to the economics of agricultural markets. The objective of the course is to apply microeconomic principles to understand the working of agricultural markets and basic strategies for farms and other agri-businesses to manage price risk. The course begins with a review of microeconomics and then covers instruments available to agri-businesses to discover prices and to manage price risks. The course then explains how storage affects prices, describes markets for livestock and poultry and explains how international markets affect US domestic agricultural markets. Depending on how much time there is left at the end of the semester, the course will look into market concentration in agriculture, marketing margins and issues with US biofuel policies. 

## Prerequisites
Econ 101 or equivalent course. This will be strictly enforced.

## Course Format and Requirements
Two lectures per week. Grades will be given according to your performance on three examinations, assignments, quizzes and attendance. The first examination will be on **September 20**, the second examination is currently scheduled on **October 25** and the final examination during the **finals week**. The exam dates might change and I will let you know well in advance if that is the case. No make-up exam or other type of arrangements will be given other than for significant reasons (e.g. medical emergency) that are out of your control and that you can document.

There are 5 assignments, with some possibly occurring concurrently. The main goal of assignments 1 to 3 is for you to learn about a commodity, keep track of its market, learn how futures trading works and learn about hedging. Assignment 1 will ask you to follow prices for corn at a selected location and on the futures market. In assignment 2, you will continue tracking the same prices and maintain a margin account. In assignment 3, you will use your futures position to hedge your cash position. Assignment 4 and 5 will be related to other material that we will cover in class.

In most classes, you will have to complete a short quiz using [Top Hat](https://old.it.iastate.edu/services/tophat). These quizzes will cover class material and current ag. market issues. It is not your performance in those quizzes that will be monitored but your participation. You can miss two classes without affecting your class participation grade. Your score for class participation will be calculated based on your attendance relative to the number of quizzes. For example, if you attend 15 classes and I run 20 quizzes, your score out of 10 will be calculated as $10*\left(\frac{15}{20-2}\right) = 8.33$. You cannot receive more than 10 points.

I am planning for three or four guest lectures given by professionals or extension economists working at the University. I will announce ahead of time when these lectures will take place. I might give one or two extra points for attending lunch with guest lecturers provided they wish to have lunch with students. These are the only extra credits that I will give in Econ 235.

The breakdown of points for the calculation of your final grade is as follow:

|**Points for calculation of final grade**|
|:-----------------------------------------|----:| 
| First exam                               | 15  | 
| Second exam                              | 15  | 
| Final exam (Finals week)                 | 20  | 
| Assignment 1 (Futures and local markets) | 5   |
| Assignment 2 (Futures and margin account)| 10  |
| Assignment 3 (Hedging with futures)      | 10  |
| Assignment 4                             | 5   |
| Assignment 5                             | 5   |
| Class participation                      | 10  |
| Guest lecture attendance                 | 5   |
|                                          |-----| 
| Total                                    | 100 |


## Learning Outcomes
Econ 235 has a course-level continuous improvement plan as required by the Iowa State legislature. Teachers of Econ 235 have identified two learning outcomes:

1. Students can apply micro-economics concepts to analyze developments in agricultural commodity markets;
2. Students can apply risk management techniques to agricultural marketing.
The implication for you is that some of the teaching in Econ 235 will target these two learning outcomes. You will be evaluated on your learning specific to these outcomes and I must report on your performance.

## Topics Outline
The list of topics is below. I do not know the exact amount of time we will spend on each topic and I do not know if we will have the time to cover all of those topics.

1. Introduction
2. Review of microeconomic
3. Futures
4. Basis
5. Hedging with futures
6. Introduction to options
8. Storage
9. Livestock
10. Poultry
11. Trade
12. Market concentration
13. Marketing margins and product quality
14. Biofuels

## Canvas
I will use Canvas to post the syllabus, the calendar, the lecture slides, assignments, quizzes, announcements and grades. You will have to turn in your assignments and take quizzes on Canvas. Please have look on Canvas before sending me an email about the course calendar.

## Textbook
There is no textbook required for this course. However, you may sometime find it useful to go back to the book you used for your principle of microeconomics course. For most of the topics of the course, I will suggest reading of material available online. I may also refer to the online textbook by Mindy Mallory available at <http://mindymallory.github.io/PriceAnalysis/>. 

## General issues

### Classroom Etiquette
Please be considerate of your peers and me. If you do not respect those around you, I may ask you to leave the classroom. Here are a few simple rules that I would like you to pay attention to:

1. No cell phone in class.
2. I will tolerate the use of laptop computers in class as I will be lecturing from slides that I make available on Blackboard. However, please avoid surfing the web, getting distracted with social websites and finishing a homework for a different class. Your computer should not become a distraction. If the use of laptops becomes a problem, I will ask that those using a computer to sit at the font of the class.
3. Do not talk with fellow students during lecture.

### Academic Dishonesty
The class will follow Iowa State University’s policy on academic dishonesty.  Anyone suspected of academic dishonesty will be reported to the Dean of Students Office.
<http://www.dso.iastate.edu/ja/academic/misconduct.html>.

### Disability Accommodation
Iowa State University complies with the Americans with Disabilities Act and Sect 504 of the Rehabilitation Act. If you have a disability and anticipate needing accommodations in this course, please contact Dr. Pouliot to set up a meeting within the first two weeks of the semester or as soon as you become aware of your need. Before meeting with Dr. Pouliot, you will need to obtain a SAAR form with recommendations for accommodations from the Student Disability Resources, located in Room 1076 on the main floor of the Student Services Building. Their telephone number is 515-294-7220 or email <disabilityresources@iastate.edu>. Retroactive requests for accommodations will not be honored.

### Dead Week
This class follows the Iowa State University Dead Week policy as noted in section 10.6.4 of the Faculty Handbook: <http://www.provost.iastate.edu/resources/faculty-handbook>.
 
### Harassment and Discrimination
Iowa State University strives to maintain our campus as a place of work and study for faculty, staff, and students that is free of all forms of prohibited discrimination and harassment based upon race, ethnicity, sex (including sexual assault), pregnancy, color, religion, national origin, physical or mental disability, age, marital status, sexual orientation, gender identity, genetic information, or status as a U.S. veteran. Any student who has concerns about such behavior should contact his/her instructor, Student Assistance at 515-294-1020, or the Office of Equal Opportunity and Compliance at 515-294-7612. 

### Religious Accommodation
If an academic or work requirement conflicts with your religious practices and/or observances, you may request reasonable accommodations. Your request must be in writing, and your instructor or supervisor will review the request.  You or your instructor may also seek assistance from the Dean of Students Office or the Office of Equal Opportunity and Compliance.

### Contact Information
If you are experiencing, or have experienced, a problem with any of the above issues, email  <academicissues@iastate.edu>.







